POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "name": "Luccao",
  "lastname": "Da Bisga",
  "cpf": "75324771260",
  "phone": "11900000000",
  "email": "lucca.mancusi@alest.com.br",
  "password": "aaaaaaA1!!"
}   
###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "bryan.soares@bisga.com",
    "password": "aaaaaaA1!"
}
###